### ISSUE TITLE
Issue with StorageClassName

### ISSUE THREAD

**Issue by chifu1234** [harvester/docker-machine-driver-harvester#7]
I can not stage because the driver prepends the image-name to the storageClass, but the storageClass does not exists. Only longhorn storageClass exists:
https://github.com/harvester/docker-machine-driver-harvester/blob/35a96257b3bf0f853899ca1f0d12ccfaa18f40f1/harvester/create.go#L109

tested with harvester 0.1.0-alpha. Maybe this will only work with 0.2.0 :).

**Comment by futuretea** [comment]
@chifu1234 support v0.1.0-alpha now

**Comment by chifu1234** [comment]
hi @futuretea thanks!
i still have issue,

```
  - metadata:
      annotations:
        cdi.kubevirt.io/storage.import.requiresScratch: "true"
        harvester.cattle.io/imageId: default/image-qgw57
      creationTimestamp: null
      name: sdf2-disk-0-54qdp
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 40Gi
        volumeMode: Filesystem
      source:
        http:
          certConfigMap: importer-ca-none
          url: http://minio.harvester-system:9000/vm-images/image-qgw57
```
I think  `storageClassName: longhorn` is missing here, but i had no time to verify it.
